### ISSUE TITLE
Fix deployment with travis-ci

### ISSUE THREAD

**Issue by SimplicityGuy** [SimplicityGuy/pynoc#10]
Currently the build in travis-ci works, but for some reason builds earlier than `1.2.2` did not include the `PowerNet-MIB.py` which causes breaks.

**Comment by SimplicityGuy** [comment]
This is still happening.

**Comment by davidhousedev** [comment]
I think this can be closed as of PR #16.

**Comment by SimplicityGuy** [comment]
`PowerNet-MIB.py` is no longer used.
